cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', AddToCartView.as_view(), name='add'),
    path('addcustomcurtain/<int:product_id>/', AddCustomCurtainToCartView.as_view(), name='addcustomCurtain'),
    path('remove/<int:product_id>/', RemoveFromCartView.as_view(), name='remove'),  
    path('update/<int:product_id>/', UpdateCartView.as_view(), name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
# from website.sitemaps import StaticViewSitemap
# from blog.sitemaps import BlogSitemap
from django.conf.urls import handler404
from azbankgateways.urls import az_bank_gateways_urls


# sitemaps = {
#     "static": StaticViewSitemap,
#     'blog': BlogSitemap
# }

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/',include('payments.urls')),
    # path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'website.views.handler404'

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('Sofa/', SofaView.as_view(), name='sofa'),
    path('Sofafabric/', SofafabricView.as_view(), name='sofafabric'),
    path('Wallcoverings/', WallcoveringsView.as_view(), name='wallcovering'),
    path('Floorcoverings/', FloorcoveringsView.as_view(), name='floorcovering'),
    path('Cornice/', CorniceView.as_view(), name='cornice'),
    path('Readycurtain/', ReadycurtainView.as_view(), name='readycurtain'),
    path('Customcurtain/', CustomcurtainView.as_view(), name='customcurtain'),
    path('zebracurtain/', ZebracurtainView.as_view(), name='zebracurtain'),
    path('<int:product_id>/', ProductDetailView.as_view(), name='product_detail'),
]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('sofas/', SofasView.as_view(), name='sofas'),

    # other paths...
]

handler404 = 'website.views.handler404'

orders/models.py
# models.py

from django.db import models
from products.models import Product
from accounts.models import User

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی")

    def __str__(self):
        return f'سفارش دهنده - {self.user}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    texture_code = models.IntegerField(verbose_name="کد تکسچر")

    def __str__(self):
        return f'{self.product}'

class Customcurtain(OrderItem):
    length = models.FloatField(null=True, blank=True, verbose_name="طول")
    quantity = models.PositiveIntegerField(default=1, verbose_name="تعداد")
    width = models.FloatField(null=True, blank=True, verbose_name="عرض")
    needs_curtain_rod = models.BooleanField(default=False, null=True, blank=True, verbose_name="نیاز به چوب پرده")

    class Meta:
        verbose_name = 'پرده سفارشی'
        verbose_name_plural = 'پرده‌های سفارشی'

    def __str__(self):
        return f'Custom Curtain - {self.product} - Quantity: {self.quantity}'

class Cornice(OrderItem):
    cornice_7 = models.PositiveIntegerField(null=True, blank=True, verbose_name='قرنیز 7 سانتی')
    cornice_9 = models.PositiveIntegerField(null=True, blank=True, verbose_name='قرنیز 9 سانتی')
    Gordeh = models.PositiveIntegerField(null=True, blank=True, verbose_name="گرده")
    Miane = models.PositiveIntegerField(null=True, blank=True, verbose_name="میانه")
    Tasho = models.PositiveIntegerField(null=True, blank=True, verbose_name="تاشو")
    Scouti = models.PositiveIntegerField(null=True, blank=True, verbose_name="اسکوتی")

    class Meta:
        verbose_name = 'قرنیز'
        verbose_name_plural = 'قرنیزها'

    def __str__(self):
        return f'Cornice - {self.product}'

class Floorcoverings(OrderItem):
    quantity = models.PositiveIntegerField(default=1, verbose_name="تعداد")
    glue_4kg = models.PositiveIntegerField(null=True, blank=True, verbose_name="چسب ۴ کیلوگرم")
    glue_10kg = models.PositiveIntegerField(null=True, blank=True, verbose_name="چسب ۱۰ کیلوگرم")

    class Meta:
        verbose_name = 'پوشش کف'
        verbose_name_plural = 'پوشش‌های کف'

    def __str__(self):
        return f'Floorcovering - {self.product} - Quantity: {self.quantity}'

class NormalProducts(OrderItem):
    quantity = models.PositiveIntegerField(default=1, verbose_name="تعداد")

    class Meta:
        verbose_name = 'محصول عادی'
        verbose_name_plural =  'محصولات عادی'

    def __str__(self):
        return f'Normal Product - {self.product} - Quantity: {self.quantity}'

products/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Product
from django.views.generic import ListView
from .models import *




class ProductDetailView(View):
    template_name = 'products/product_detail/product_detail.html'

    def get_class_name_for_record(self, record_id):
        try:
            cornice = Cornice.objects.get(id=record_id)
            return 'cornice', cornice
        except Cornice.DoesNotExist:
            pass

        try:
            floorcoverings =Floorcoverings.objects.get(id=record_id)
            return 'Floorcoverings', floorcoverings
        except Floorcoverings.DoesNotExist:
            pass

        try:
            custom_curtain = Customcurtain.objects.get(id=record_id)
            return 'Customcurtain', custom_curtain
        except Customcurtain.DoesNotExist:
            pass

        return None, None

    def get(self, request, product_id, *args, **kwargs):
        class_name, products = self.get_class_name_for_record(product_id)
        print(f"class name : {class_name}")

        if class_name=='cornice':
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product,'cornice': products, 'class_name': class_name}
        elif class_name=='Customcurtain':
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product,'custom_curtain':products, 'class_name': class_name}
        elif class_name=='Floorcoverings':
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product,'Floorcoverings':products, 'class_name': class_name}
        else:
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product, 'class_name': class_name}

        return render(request, self.template_name, context)

    
class SofaView(View):
    template_name = 'products/product_home/sofa.html'

    def get(self, request, *args, **kwargs):
        sofas = Sofa.objects.all()
        context = {'sofas': sofas}
        return render(request, self.template_name, context)
    
class SofafabricView(View):
    template_name = 'products/product_home/sofafabric.html'

    def get(self, request, *args, **kwargs):
        sofafabrics = Sofafabric.objects.all()
        context = {'sofafabrics': sofafabrics}
        return render(request, self.template_name, context)
    
class WallcoveringsView(View):
    template_name = 'products/product_home/wallcovering.html'

    def get(self, request, *args, **kwargs):
        wallcoverings = Wallcoverings.objects.all()
        context = {'wallcoverings': wallcoverings}
        return render(request, self.template_name, context)
    
class FloorcoveringsView(View):
    template_name = 'products/product_home/floorcovering.html'

    def get(self, request, *args, **kwargs):
        floorcoverings = Floorcoverings.objects.all()
        context = {'floorcoverings': floorcoverings}
        return render(request, self.template_name, context)
    
class CorniceView(View):
    template_name = 'products/product_home/cornice.html'

    def get(self, request, *args, **kwargs):
        cornices = Cornice.objects.all()
        context = {'cornices': cornices}  
        return render(request, self.template_name, context)

class ReadycurtainView(View):
    template_name = 'products/product_home/Readycurtain.html'

    def get(self, request, *args, **kwargs):
        readycurtains = Readycurtain.objects.all()
        context = {'readycurtains': readycurtains}
        return render(request, self.template_name, context)
    
class CustomcurtainView(View):
    template_name = 'products/product_home/customcurtain.html'

    def get(self, request, *args, **kwargs):
        customcurtains = Customcurtain.objects.all()
        context = {'customcurtains': customcurtains}
        return render(request, self.template_name, context)
    
class ZebracurtainView(View):
    template_name = 'products/product_home/zebracurtain.html'

    def get(self, request, *args, **kwargs):
        Zebracurtains = Zebracurtain.objects.all()
        context = {'Zebracurtains': Zebracurtains}
        return render(request, self.template_name, context)





class SearchResultsView(ListView):
    model = Product
    template_name = 'products/search_results.html'
    context_object_name = 'results'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        return Product.objects.filter(title__icontains=query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context

templates/products/product_detail/customcurtain.html
<div class="w-full h-14 flex gap-5 items-center">
    <span class="text-primary text-lg md:text-xl font bold">
      طول پرده
    </span>
  </div>
  <label class="relative flex h-14 rounded-lg overflow-hidden">
    <input
      type="number"
      name="length"
      id="curtainHeight"
      data-price="10000"
      class="w-full bg-tertiary mx-auto px-5 placeholder:text-lg font-semibold placeholder:text-senary placeholder:mx-auto text-center !outline-none !border-none"
      placeholder="طول پرده" />
  </label>
  <div class="w-full h-14 flex gap-5 items-center">
    <span class="text-primary text-lg md:text-xl font bold">
      عرض پرده
    </span>
  </div>
  <label class="relative flex h-14 rounded-lg overflow-hidden">
    <input
      type="number"
      name="width"
      id="curtainWidth"
      data-price="10000"
      class="w-full bg-tertiary mx-auto px-5 placeholder:text-lg font-semibold placeholder:text-senary placeholder:mx-auto text-center !outline-none !border-none"
      placeholder="عرض پرده" />
  </label>
  <div
    class="w-full h-14 flex gap-5 items-center col-span-2 md:col-span-1">
    <span class="text-primary text-lg md:text-xl font bold">
      آیا چوب پرده نیاز دارید ؟
    </span>
    {% if user.is_authenticated %}
    {% if user.customer_type == 'wholesale' %}
    <!-- ------------------------ -->
    <input
    type="checkbox"
    name="needs_curtain_rod"
    id="certainWood"
    data-price="{{ custom_curtain.curtain_rod.price_wholesale }}"
    class="size-5 group" />
    <div class="h-full bg-white"></div>
    <!-- ------------------------ -->
  {% else %}
    <!-- ------------------------ -->
      <input
      type="checkbox"
      name="needs_curtain_rod"
      id="certainWood"
      data-price="{{ custom_curtain.curtain_rod.price_retail }}"
      class="size-5 group" />
      <div class="h-full bg-white"></div>
    <!-- ------------------------ -->
    {% endif %}
    {% else %}
    <!-- ------------------------ -->
    <input
    type="checkbox"
    name="needs_curtain_rod"
    id="certainWood"
    data-price="{{ custom_curtain.curtain_rod.price_retail }}"
    class="size-5 group" />
    <div class="h-full bg-white"></div>
    <!-- ------------------------ -->
    {% endif %}

  </div>
  <label class="relative flex h-14 rounded-lg overflow-hidden">
    <input
      type="number"
      name="quantity"
      value="1"
      id="orderNumber"
      class="w-full bg-tertiary mx-auto px-5 placeholder:text-lg font-semibold placeholder:text-senary placeholder:mx-auto text-center !outline-none !border-none"
      placeholder="تعداد" />
  </label>
  <div
    class="w-full col-span-2 md:col-span-1 flex justify-between items-center">
    <div class="md:text-sm">
      قیمت نهایی:
      <span
        class="text-primary text-2xl md:text-sm font bold"
        id="totalPrice"
        >0</span
      >
      <span class="text-primary text-2xl md:text-sm font bold"
        >تومان</span
      >
    </div>

templates/products/product_detail/product_detail.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>طراحان</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="shortcut icon" href="{% static '/assets/tarahanIcon-thsqZuN2.svg' %}" type="image/x-icon">
    <link rel="stylesheet" crossorigin href="{% static '/assets/alert.css' %}">
  <link rel="stylesheet" crossorigin href="{% static '/assets/output-xplU_3MA.css' %}">
</head>
<body dir="rtl">
  {% include 'nav.html' %}
    <nav class="w-full h-14 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.15)] px-4 hidden lg:flex justify-between items-center relative">
      <a href="{% url 'website:home' %}">
      <img src="{% static '/images/tarahanIcon.svg' %}" alt="" class="size-10 aspect-square">
      </a>
      <button class="flex flex-col justify-around w-6 h-6 bg-transparent border-none cursor-pointer z-10 focus:outline-none" id="hamburger">
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
      </button>    
    </nav>
    {% include 'Phone.html' %}
    <section class="px-36 2xl:px-10 py-4 bg-secondary h-28 flex justify-center md:!px-3 md:h-fit md:py-2 ">
        <div class="w-full h-full bg-secondary ">
            <h1 class="text-3xl font-extrabold text-primary md:text-lg">
                دکوراسیون
            </h1>
            <div class="w-full h-fit flex items-center gap-1 text-xl font-normal text-primary mt-2 cursor-pointer md:text-sm">
                <a href="{% url 'website:home' %}">
                    خانه
                </a>
                <img src="data:image/svg+xml,%3csvg%20width='22'%20height='22'%20viewBox='0%200%2022%2022'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%3e%3crect%20width='22'%20height='22'%20transform='matrix(1%200%200%20-1%200%2022)'%20fill='url(%23pattern0)'/%3e%3cdefs%3e%3cpattern%20id='pattern0'%20patternContentUnits='objectBoundingBox'%20width='1'%20height='1'%3e%3cuse%20xlink:href='%23image0_638_2126'%20transform='scale(0.0192308)'/%3e%3c/pattern%3e%3cimage%20id='image0_638_2126'%20width='52'%20height='52'%20xlink:href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAYAAADFeBvrAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtElEQVR4nO3ZwQnCQBCF4alJD7Ggt38NuXm1WcUOFFHQg4mKh51Z3gdbwM9MwpJEmJmZLQMmYI4RSNq21k7ApbV2iFFieJyyUXoTUzZKKzHlori/AM5rMS9nLj8ZnucWPUVWckxS8mSSkieTlDyZpOTJJCVPJjFgAxy/vWxK2kV2OApPqhu8fnj9uvH64fXrx+uH16+foT4F//hM7aMS1qNqxXyIqhmzEFU7ZsifxmZmFn+6Ajj7X4aUiCzdAAAAAElFTkSuQmCC'/%3e%3c/defs%3e%3c/svg%3e" class="size-4" alt="">
                <a>دکوراسیون</a>
            </div>
        </div>
    </section>
    <main class="w-full h-fit px-48 2xl:px-16 md:!px-0 py-10 md:py-5 flex flex-col gap-10 md:gap-5 items-center bg-tertiary">
      <section class="md:w-11/12 w-10/12 md:grid-rows-auto rounded-3xl bg-secondary h-fit grid grid-cols-3 md:grid-cols-1 gap-10 md:gap-5 p-8 md:p-4 md:flex-col-reverse">
        <div class="w-full col-span-2 md:col-span-1 md:w-full min-h-full h-full flex flex-col  justify-between">
          <div class="w-full flex flex-col gap-5">
            <div class="w-full flex justify-between">
              <h2 class="text-primary text-3xl md:text-xl font-extrabold">{{product.title}}</h2>
              <h5 class="text-primary text-lg  font-bold flex justify-center items-center">کد محصول: <span class="mr-5">{{product.product_code}}</span></h5>
            </div>
            <ul class="list-disc pr-10 text-primary text-lg md:text-base font-medium">
              {% if product.dimensions.length %}
                <li>
                  طول : {{ product.dimensions.get_length_display }}
                </li>
              {% endif %}
              {% if product.dimensions.width %}
                <li>
                  عرض : {{ product.dimensions.get_width_display }}
                </li>
              {% endif %}
              {% if product.dimensions.thickness %}
                <li>
                  ضخامت : {{ product.dimensions.get_thickness_display }}
                </li>
              {% endif %}
              <li>
                {{ product.description }}
              </li>
            </ul>
            
          </div>
          {% if class_name != 'cornice'  %}
          <div class="w-full flex flex-col items-end">
            {% if user.is_authenticated %}
            {% if user.customer_type == 'wholesale' %}
              <span class="w-fit">
                قیمت هر {{ product.price.get_translated_unit }} : <span class="text-primary text-2xl md:text-sm font-bold"> {{ product.price.price_wholesale|intcomma }} تومان</span>
              </span>
            {% else %}
              <span class="w-fit">
                قیمت هر {{ product.price.get_translated_unit }} : <span class="text-primary text-2xl md:text-sm font-bold"> {{ product.price.price_retail|intcomma }} تومان</span>
              </span>
            {% endif %}
          {% else %}
            <span class="w-fit">
              قیمت هر {{ product.price.get_translated_unit }} : <span class="text-primary text-2xl md:text-sm font bold"> {{ product.price.price_retail|intcomma }} تومان</span>
            </span>
          {% endif %}
          
          </div>
          {% endif %}
        </div>
        <div class="w-full col-span-1 md:col-span-1 md:-order-1 md:w-full md:max-h-52 aspect-square md:pb-0 flex flex-col md:flex-row rounded-3xl bg-white pb-2">
          <img id="mainImage" src="{{ product.images.first.image.url }}" class="w-full md:w-[calc(100%-3.5rem)] md:aspect-video h-full aspect-square rounded-3xl object-cover" alt="{{ product.title }}">
          <div class="md:py-2">
            <div class="w-full md:w-14 h-fit md:h-full flex overflow-y-scroll md:flex-col md:overflow-x-scroll gap-2 md:mt-0 mt-2 px-2 items-center removeScrollBar" id="scrollableDiv">
              {% for image in product.images.all %}
                <img src="{{ image.image.url }}" onclick="changeMainImage('{{ image.image.url }}')" class="size-14 aspect-square rounded-lg object-cover" alt="">
              {% endfor %}
            </div>
          </div>
        </div>       
          </div>
        </div>
        
      </section>
      <form method="post" action="{% url 'cart:add' product_id=product.id %}" class="w-10/12 md:w-11/12 h-fit bg-secondary p-10 md:p-5 grid grid-cols-2 md:grid-cols-1 gap-5 rounded-4xl">
        {% csrf_token %}
        {% if class_name == 'Customcurtain' %}
          {% include 'products/product_detail/customcurtain.html' %}
        {% endif %}
        {% if class_name == 'cornice' %}
            {% include 'products/product_detail/cornice.html' %}
        {% endif %}
        {% if class_name == 'Floorcoverings' %}
            {% include 'products/product_detail/floorcoverings.html' %}
        {% endif %}
        {% if class_name == None %}
        <label class="relative flex h-14 rounded-lg overflow-hidden">
          <input
            type="number"
            name="quantity"
            value="1"
            id="orderNumber"
            class="w-full bg-tertiary mx-auto px-5 placeholder:text-lg font-semibold placeholder:text-senary placeholder:mx-auto text-center !outline-none !border-none"
            placeholder="تعداد" />
        </label>
        {% endif %}


            <div class="w-full h-14 flex gap-5 items-center">
                <button id="colorButton" class="text-primary bg-tertiary px-5 py-1 rounded-lg text-lg md:text-xl font bold">انتخاب رنگ</button>
                <input type="radio" name="color" id="color1" class="size-5" hidden>
                <input type="text" name="texture_code" value="{{product.textures.first}}" id="textureInput" class="size-5" hidden>
                <img src="{{ product.textures.first.image.url }}" class="size-14 object-cover rounded-xl" alt="" id="texturePreview">
            </div>
        </div>
        <!-- <-------- -->
        {% if class_name == 'cornice' and 'Floorcoverings' %}
        <div class="w-full col-span-2 md:col-span-1 flex justify-between items-center">
     
          <input type="hidden" name="product_id" value="{{ product.id }}">
          <!-- new -->
          <div
            class="w-full col-span-2 md:col-span-1 flex justify-between items-center">
            <div class="md:text-sm">
              قیمت نهایی:
              <span
                class="text-primary text-2xl md:text-sm font bold"
                name="price"
                id="totalPrice"
                >0</span
              >
              <span class="text-primary text-2xl md:text-sm font bold"
                >تومان</span
              >
            </div>
            </div>
          <!-- new -->
          <button class="bg-white rounded-lg flex justify-center items-center md:text-sm md:px-3 px-5 py-2 font-extrabold text-xl text-senary">
            افزودن به سبد خرید
          </button>
    
        </div>
        {% endif %}
        <!-- -----Customcurtain----- -->
        {% if class_name == 'Customcurtain' %}
          <input type="hidden" name="product_id" value="{{ product.id }}">
          <button class="bg-white rounded-lg flex justify-center items-center md:text-sm md:px-3 px-5 py-2 font-extrabold text-xl text-senary">
            افزودن به سبد خرید
          </button>
        </div>
        {% endif %}

        <!-- -----Customcurtain----- -->

        {% if class_name != 'Customcurtain' and class_name != 'cornice' %}
        <div class="w-full col-span-2 md:col-span-1 flex justify-between items-center">
     
          <input type="hidden" name="product_id" value="{{ product.id }}">
          <!-- <input type="hidden" name="price" min="0" value="1700"> -->
          <!-- new -->
          <div
            class="w-full col-span-2 md:col-span-1 flex justify-between items-center">
            <div class="md:text-sm">
              قیمت نهایی:
              <span
                class="text-primary text-2xl md:text-sm font bold"
                id="totalPrice"
                >0</span
              >
              <span class="text-primary text-2xl md:text-sm font bold"
                >تومان</span
              >
            </div>
            </div>
            <button class="bg-white rounded-lg flex justify-center items-center md:text-sm md:px-3 px-5 py-2 font-extrabold text-xl text-senary">
              افزودن به سبد خرید
            </button>
          </div>
        {% endif %}
        </form>
      </section>
    </main>
    
    {% include 'footer.html' %}
  <script src="{% static 'js/texturePreview.js' %}" defer></script>
  <script src="{% static 'js/product.js' %}" defer></script>

<dialog id="colorDialog" class="w-fit h-fit">
  <div class="w-full bg-quinary h-10 px-3 shadow-3xl flex items-center text-primary text-xl font bold">
    انتخاب رنگ
  </div>
  <div class="grid grid-cols-5 gap-5 p-3">
    {% for texture in product.textures.all %}
      <div class="chooseTexture" data-src="{{ texture.image.url }}" data-id="{{ texture}}">
        <div class="w-full">
          <img src="{{ texture.image.url }}" class="size-14 object-cover rounded-xl" alt="{{ texture}}" data-id="{{ texture }}">
          <span class="w-full text-center">
            {{ product.product_code }}{{ texture.code }}
          </span>
        </div>
      </div>
  {% endfor %}
  </div>
</dialog>
  <script>
    document.getElementById('toggleCorniceTypes').addEventListener('click', function() {
        var typesContainer = document.querySelectorAll('.types-container');
        typesContainer.forEach(function(container) {
            container.style.display = container.style.display === 'none' ? 'flex' : 'none';
        });
    });
  </script>
      <script type="module" crossorigin src="{% static '/assets/output-22b6PNpL.js' %}"></script>
      <script type="module" crossorigin src="{% static '/assets/main-Acrfd2WL.js' %}"></script>
    <script>
        document.getElementById('colorButton').addEventListener('click', function(event) {
            event.preventDefault(); // Prevent the default form submission
            // Your logic for handling color selection goes here
        });
    </script>
    <script>
              function changeMainImage(newImageUrl) {
                // Get the main image element
                var mainImage = document.getElementById('mainImage');
                
                // Change the source of the main image to the clicked image
                mainImage.src = newImageUrl;
              }
    </script>
    
    <script src="{% static 'js/cornice_price.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
</body>
</html>




              
              