cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', AddToCartView.as_view(), name='add'),
    path('addcustomcurtain/<int:product_id>/', AddCustomCurtainToCartView.as_view(), name='addcustomCurtain'),
    path('remove/<int:product_id>/', RemoveFromCartView.as_view(), name='remove'),  
    path('update/<int:product_id>/', UpdateCartView.as_view(), name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
# from website.sitemaps import StaticViewSitemap
# from blog.sitemaps import BlogSitemap
from django.conf.urls import handler404
from azbankgateways.urls import az_bank_gateways_urls


# sitemaps = {
#     "static": StaticViewSitemap,
#     'blog': BlogSitemap
# }

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/',include('payments.urls')),
    # path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'website.views.handler404'

orders/urls.py
from django.urls import path
from .views import OrderCreateView

app_name = 'orders'


urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    # Add more views/urls as needed
]










# # orders/urls.py
# from django.urls import path
# from .views import OrderView, PaymentView, OrderSuccessView

# app_name = 'orders'

# urlpatterns = [
#     path('create/', OrderView.as_view(), name='create_order'),
#     path('<int:order_id>/payment/', PaymentView.as_view(), name='payment'),
#     path('<int:order_id>/success/', OrderSuccessView.as_view(), name='order_success'),
# ]

payments/urls.py
from django.urls import path
from .views import *

app_name = 'payments'

urlpatterns = [
    path('go_to_gatway', go_to_gateway_view, name='payment'),
    path('callback', callback_gateway_view, name='callback'),
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('Sofa/', SofaView.as_view(), name='sofa'),
    path('Sofafabric/', SofafabricView.as_view(), name='sofafabric'),
    path('Wallcoverings/', WallcoveringsView.as_view(), name='wallcovering'),
    path('Floorcoverings/', FloorcoveringsView.as_view(), name='floorcovering'),
    path('Cornice/', CorniceView.as_view(), name='cornice'),
    path('Readycurtain/', ReadycurtainView.as_view(), name='readycurtain'),
    path('Customcurtain/', CustomcurtainView.as_view(), name='customcurtain'),
    path('zebracurtain/', ZebracurtainView.as_view(), name='zebracurtain'),
    path('<int:product_id>/', ProductDetailView.as_view(), name='product_detail'),
]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('sofas/', SofasView.as_view(), name='sofas'),

    # other paths...
]

handler404 = 'website.views.handler404'

cart/models.py
# # models.py
# from django.conf import settings
# from django.db import models
# from products.models import *
# from django.db.models.signals import post_save
# from django.dispatch import receiver
 
# class Cart(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart', verbose_name='کاربر')
#     created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

#     class Meta:
#         verbose_name = 'سبد خرید'
#         verbose_name_plural = 'سبدهای خرید'

#     def __str__(self):
#         # user_info = f"{self.user.phone_number}" if self.user and hasattr(self.user, 'phone_number') else "Anonymous User"
#         # return f"Cart for {user_info}"
#         return "cart"
# @receiver(post_save, sender=Cart)
# def create_cart(sender, instance, created, **kwargs):
#     """
#     Signal receiver for creating a CartItem instance when a Cart is created.
#     """
#     if created:
#         print(f"Cart created for user: {instance.user}")
#         CartItem.objects.create(cart=instance)
#         print(f"CartItem created for Cart: {instance}")

# class CartItem(models.Model):
#     cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items', verbose_name='سبد خرید')
#     product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
#     quantity = models.PositiveIntegerField(default=1, verbose_name='تعداد')
#     texture = models.ForeignKey(Texture, on_delete=models.CASCADE, null=True, blank=True, related_name='cart_items', verbose_name='تکسچر ')
#     # custom_curtain_info = models.OneToOneField(Customcurtain, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='اطلاعات پرده سفارشی')

#     class Meta:
#         verbose_name = 'آیتم سبد خرید'
#         verbose_name_plural = 'آیتم‌های سبد خرید'

#     def __str__(self):
#         return f"{self.quantity} x {self.product.title} ({self.selected_texture.code}) in {self.cart.user.phone_number}'s cart"

cart/forms.py
# cart/forms.py

from django import forms

class CustomCurtainForm(forms.Form):
    length = forms.DecimalField(label='طول', min_value=0, required=True)
    width = forms.DecimalField(label='عرض', min_value=0, required=True)
    number_of_panels = forms.IntegerField(label='تعداد پنل', min_value=1, required=True)
    needs_curtain_rod = forms.BooleanField(label='نیاز به چوب پرده', required=False)

class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1, required=False, widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'تعداد'}))
    product_id = forms.IntegerField(widget=forms.HiddenInput())
    price = forms.IntegerField(required=False,widget=forms.HiddenInput(),initial=0 )
    length = forms.DecimalField(required=False)
    width = forms.DecimalField(required=False)
    number_of_panels = forms.IntegerField(required=False)
    needs_curtain_rod = forms.BooleanField(required=False)
    texture_code = forms.CharField(max_length=50, widget=forms.HiddenInput())
    cornice_7 = forms.DecimalField(required=False,)
    cornice_9 = forms.DecimalField(required=False,)
    Gordeh = forms.DecimalField(required=False,)
    Miane = forms.DecimalField(required=False,)
    Tasho = forms.DecimalField(required=False,)
    Scouti = forms.DecimalField(required=False,)
    glue_4kg = forms.DecimalField(required=False,)
    glue_10kg = forms.DecimalField(required=False,)


    custom_curtain_form = CustomCurtainForm()

class UpdateCartForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        max_value=100,  # Adjust the maximum value as needed
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

cart/views.py
# cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.views import View
from .forms import *
from products.models import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from orders.models import Order 
from .cart import Cart
from products.views import ProductDetailView
# from .models import CartItem

class CartView(View):
    template_name = 'cart/cart.html'

    def get(self, request):
        cart = Cart(request)
        # cart.clear()
        context = {
            'cart': cart,  # Pass the entire cart object to the template
        }
        return render(request, self.template_name, context)

class AddToCartView(View):
    template_name = 'products/product_detail/product_detail.html'

    def post(self, request, product_id):
        products = get_object_or_404(Product, pk=product_id)
        form = AddToCartForm(request.POST)

        product_detail=ProductDetailView()
        product_type,product=product_detail.get_class_name_for_record(product_id)

        if product== None :
            # print('product is ::::',product)
            product=products
        # print("Raw Form Data:", request.POST)  # Print raw form data for debugging
        # # Debugging: Print form data before validation
        # print("Quantity:", form.data.get('quantity'))
        # print("Texture Code:", form.data.get('texture_code'))

        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            texture_code = form.cleaned_data['texture_code']
            length = form.cleaned_data['length']
            width = form.cleaned_data['width']
            needs_curtain_rod = form.cleaned_data['needs_curtain_rod']
            cornice_7 = form.cleaned_data['cornice_7']
            cornice_9 = form.cleaned_data['cornice_9']
            Gordeh = form.cleaned_data['Gordeh']
            Miane = form.cleaned_data['Miane']
            Tasho = form.cleaned_data['Tasho']
            Scouti = form.cleaned_data['Scouti']
            glue_4kg = form.cleaned_data['glue_4kg']
            glue_10kg = form.cleaned_data['glue_10kg']

            # print(length,width,needs_curtain_rod)
            # print(cornice_7,cornice_9,Gordeh,Miane,Tasho,Scouti)
            cart = Cart(request)
            cart.add(
                request,
                product,
                quantity,
                texture_code,
                length,
                width,
                needs_curtain_rod,
                cornice_7,
                cornice_9,
                Gordeh,
                Miane,
                Tasho,
                Scouti,
                glue_4kg,
                glue_10kg,
                product_type,
            )

            messages.success(request, f" محصول با تکسچر {texture_code} به سبد خرید شما اضافه شد.")
            return redirect('cart:cart')
        else:
            print("Invalid Form Data:", form.errors)  # Print form errors for debugging
            # return redirect('products:product_detail')
            messages.warning(request, "شما اطلاعات را درست وارد نکرده اید")

            return redirect('products:cornice')
        



class RemoveFromCartView(View):
    def post(self, request, product_id, *args, **kwargs):
        cart = Cart(request)
        removed_product=cart.remove_item(request, product_id)
        print('removed_product',removed_product)
        if removed_product:
            messages.success(request,"یک محصول از سبد شما حذف شد")
        else:
            messages.warning(request, "محصول از سبد شما حذف نشد")

        return redirect('cart:cart')

class UpdateCartView(View):
    template_name = 'cart/update_cart.html'

    def get_class_name_for_record(self,record_id):
        # try:
        #     product = Product.objects.get(id=record_id)
        #     return 'Product'
        # except Product.DoesNotExist:
        #     pass

        try:
            cornice = Cornice.objects.get(id=record_id)
            return 'cornice'
        except Cornice.DoesNotExist:
            pass

        try:
            custom_curtain = Customcurtain.objects.get(id=record_id)
            return 'Customcurtain'
        except Customcurtain.DoesNotExist:
            pass
        # If the record is not found in any class
        return None

    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, pk=product_id)
        initial_quantity = cart.get_price_for_product(product)
        initial_texture = cart.get_texture(product)  # Add method to get selected texture
        class_name =class_name = self.get_class_name_for_record(product_id)


        form = UpdateCartForm(initial={'quantity': initial_quantity, 'texture': initial_texture})

        context = {
            'form': form,
            'product': product,
            'class_name': class_name,
        }

        return render(request, self.template_name, context)

    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, pk=product_id)

        form = UpdateCartForm(request.POST)

        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            texture = form.cleaned_data['texture']

            # Check if the product is a custom curtain or a general product
            if product.is_custom_curtain:
                # Update custom curtain information
                cart.update_custom_curtain(product, quantity, texture)
            else:
                # Update general product information
                cart.update(product, quantity, texture=texture)

            messages.success(request, f"تغییرات به سبد خرید شما اعمال شد.")
            return redirect('cart:cart')

        context = {
            'form': form,
            'product': product,
        }

        return render(request, self.template_name, context)
    





class AddCustomCurtainToCartView(View):
    template_name = 'products/product_detail/product_detail.html'

    def post(self, request, product_id):
        cart = Cart(request)  # Ensure that you are correctly initializing the Cart object
        product = get_object_or_404(Product, pk=product_id)
        form = CustomCurtainForm(request.POST)
        context = {'product': product}

        if form.is_valid():
            length = form.cleaned_data['length']
            width = form.cleaned_data['width']
            number_of_panels = form.cleaned_data['number_of_panels']
            needs_curtain_rod = form.cleaned_data['needs_curtain_rod']

            custom_curtain_product = Customcurtain(
                title=product.title,
                category=product.category,
                price=product.price,
                dimensions=product.dimensions,
                curtain_rod=True,
                curtain_model="Your Model",
                side_fabric="Your Fabric",
            )

            # Add custom_curtain_product to the cart
            custom_curtain_info={'length': length,'width': width,'number_of_panels': number_of_panels,'needs_curtain_rod': needs_curtain_rod,}
            cart.add_custom_curtain(request,custom_curtain_product,1,custom_curtain_info)
            messages.success(request, "پرده سفارشی به سبد خرید شما اضافه شد.")
            return redirect('cart:cart')
        else:
            messages.error(request, "لطفاً اطلاعات معتبر وارد کنید.")
            return render(request, self.template_name, context)



class FinalizeOrderView(View):
    template_name = 'cart/finalize_order.html'

    @method_decorator(login_required, name='dispatch')
    def get(self, request):
        cart = Cart(request)

        # Additional logic to handle order finalization
        # You can create an Order instance and associate it with the user

        # For example:
        order = Order.objects.create(user=request.user, total_amount=cart.get_total())
        for item in cart:
            product = get_object_or_404(Product, pk=item['product_id'])
            quantity = item['quantity']
            order.items.create(product=product, quantity=quantity)

        # Clear the cart after finalizing the order
        cart.clear()

        context = {
            'order': order,
        }

        return render(request, self.template_name, context)

templates/cart/cart.html
{% load static %}
{% load humanize %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>طراحان</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="shortcut icon" href="{% static '/assets/tarahanIcon-thsqZuN2.svg' %}" type="image/x-icon">
  <script type="module" crossorigin src="{% static '/assets/output-22b6PNpL.js' %}"></script>
  <script type="module" crossorigin src="{% static '/assets/main-Acrfd2WL.js' %}"></script>
  <link rel="stylesheet" crossorigin href="{% static '/assets/alert.css' %}"> 
  <link rel="stylesheet" crossorigin href="{% static 'js/alert.js' %}"> 
  <link rel="stylesheet" crossorigin href="{% static '/assets/output-xplU_3MA.css' %}">
</head>
<body dir="rtl">
  {% include 'nav.html' %}
    <nav class="w-full h-14 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.15)] px-4 hidden lg:flex justify-between items-center relative">
      <a href="{% url 'website:home' %}">
      <img src="{% static '/images/tarahanIcon.svg' %}" alt="" class="size-10 aspect-square">
      </a>
      <button class="flex flex-col justify-around w-6 h-6 bg-transparent border-none cursor-pointer z-10 focus:outline-none" id="hamburger">
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
      </button>    
    </nav>
    {% include 'Phone.html' %}
    <section class="px-36 2xl:px-10 py-4 bg-secondary h-28 flex justify-center md:!px-3 md:h-fit md:py-2 ">
        <div class="w-full h-full bg-secondary ">
        <a href="{% url 'cart:cart' %}" class="group">
            <h1 class="text-3xl font-extrabold text-primary md:text-lg">
                سبد خرید
            </h1>
        </a>
        </div>
    </section>
    <main class="w-full h-fit px-48 2xl:px-16 md:!px-0 py-10 md:py-5 flex flex-col gap-10 md:gap-5 items-center bg-tertiary">
      {% if cart %}
      {% for item in cart %}
      <section class="md:w-11/12 w-10/12 md:grid-rows-auto rounded-3xl bg-secondary h-fit grid grid-cols-3 md:grid-cols-1 gap-10 md:gap-5 p-8 md:p-4 md:flex-col-reverse">
        <div class="w-full col-span-2 md:col-span-1 md:w-full min-h-full h-full flex flex-col  justify-between">
          <div class="w-full flex flex-col gap-5">
            <div class="w-full flex justify-between">
              <a href="{% url 'products:product_detail' product_id=item.product.id %}">
              <h2 class="text-primary text-3xl md:text-xl font-extrabold">{{ item.product.title }}</h2>
              </a>
              <h5 class="text-primary text-lg  font-bold flex justify-center items-center">کد محصول:<span class="mr-5">{{ item.product_code }}</span></h5>
            </div>
            <!-- ... (other code) ... -->
            <!-- <img src="{{ item.texture_image_url }}" alt="Texture Image"> -->
            <div class="w-full h-14 flex gap-5 items-center">
              <!-- <a href="{% url 'cart:update' item.product.id %}"> -->
                <button id="colorButton" class="text-primary bg-tertiary px-5 py-1 rounded-lg text-lg md:text-xl font bold">رنگ انتخاب شده</button>
              <!-- </a> -->
              <img src="{{ item.texture_image_url }}" class="size-14 object-cover rounded-xl" alt="" id="texturePreview">
            </div>            
            <!-- ... (other code) ... -->
            <ul class="list-disc pr-10 text-primary text-lg md:text-base font-medium">
              {% if item.cornice_7 %}
              <li>
                قرنیز 7 سانتی: {{ item.cornice_7 }} {{ item.product.price.get_translated_unit }} 
              </li>
              {% endif %}
              {% if item.cornice_9 %}
              <li>
                قرنیز 9 سانتی: {{ item.cornice_9 }} {{ item.product.price.get_translated_unit }} 
              </li>
              {% endif %}
              {% if item.product_type != 'Customcurtain' %}
              {% if item.product_length %}
                <li>
                  طول: {{ item.product.dimensions.get_length_display }}
                </li>
              {% endif %}
              {% if item.product_width %}
              <li>
                عرض: {{ item.product.dimensions.get_width_display }}
              </li>
              {% endif %} 
              {% endif %}
              {% if item.width %}
                <li>
                  عرض: {{ item.width }} 
                </li>
              {% endif %} 
              {% if item.product.dimensions.thickness %}
                <li>
                  ضخامت: {{ item.product.dimensions.get_thickness_display }}
                </li>
              {% endif %}
              {% if item.product_type == 'cornice' %}
              <br>
              <span class="text-primary text-lg md:text-sm font-bold">
                لوازم قرنیز :
              </span>
                {% if item.Gordeh %}
                <li>
                  گرده : {{ item.Gordeh }} عدد
                </li>
                {% endif %} 
                {% if item.Miane %}
                <li>
                  میانه : {{ item.Miane }} عدد
                </li>
                {% endif %} 
                {% if item.Tasho %}
                <li>
                  تاشو : {{ item.Tasho }} عدد
                </li>
                {% endif %} 
                {% if item.Scouti %}
                <li>
                  اسکوتیا : {{ item.Scouti }} عدد
                </li>
                {% endif %} 
              {% endif %} 
              {% if item.product_type != 'cornice' %}
              {% if item.quantity %}
              <li>
                تعداد : {{ item.quantity }}
              </li>
              {% endif %}
              {% endif %}
              {% if item.product_type == 'Floorcoverings' %}
              <br>
              <span class="text-primary text-lg md:text-sm font-bold">
                چسب:
              </span>
                {% if item.glue_4kg %}
                <li>
                  چسب 4 کیلویی : {{ item.glue_4kg }} عدد
                </li>
                {% endif %} 
                {% if item.glue_10kg %}
                <li>
                  چسب 10 کیلویی : {{ item.glue_10kg }} عدد
                </li>
                {% endif %} 
              {% endif %}
              {% if item.length %}
                <li>
                  طول: {{ item.length }} 
                </li>
              {% endif %}
              {% if item.needs_curtain_rod %}
                <li>
                  نیاز به چوب پرده: بله
                </li>
              {% endif %}
              <!-- {% if item.description %}
              <li>
                توضیحات: {{ item.description }}
              </li>
              {% endif %} -->
            </ul>
            
               <span class="text-primary text-lg md:text-sm font-bold">
              قیمت : {{ item.item_price|intcomma }} تومان
               </span>
          </div>
          <div class="w-full flex flex-col items-end">
            <form method="post" action="{% url 'cart:remove' item.product.id %}">
              {% csrf_token %}
              <button type="submit" class="w-fit px-6 py-2 rounded-xl bg-quinary text-primary text-xl md:text-base font-bold">
                  حذف محصول
              </button>
          </form>
          </div>
        </div>
        <div class="w-full col-span-1 md:col-span-1 md:-order-1 md:w-full md:max-h-52 aspect-square flex flex-col md:flex-row rounded-3xl bg-white ">
          <a href="{% url 'products:product_detail' product_id=item.product.id %}">
          <img src="{{ item.image_url }}" class="w-full md:w-[calc(100%-3.5rem)] md:aspect-video h-full aspect-square rounded-3xl object-cover" alt="{{ item.product.title }}">
          </a>
        </div>  
      </section>
      {% endfor %}
      <span class="text-primary text-lg md:text-sm font-bold">
        قیمت نهایی : {{ cart.get_total_price|intcomma }} تومان
         </span>
      <form method="post" action="{% url 'payments:payment' %}">
        {% csrf_token %}
        <button type="submit" class="w-fit px-6 py-2 rounded-xl bg-quinary text-primary text-xl md:text-base font-bold">
          پرداخت
        </button>
    </form>
      <!-- <form method="post" action="{% url 'orders:create' %}">
        {% csrf_token %}
        <button type="submit" class="w-fit px-6 py-2 rounded-xl bg-quinary text-primary text-xl md:text-base font-bold">
          پرداخت
        </button>
       </form> -->
      {% else %}
      <p class="text-primary text-2xl font-bold">سبد خرید شما خالی است</p>
      {% endif %}
    </main>
    {% include 'footer.html' %}
</body>
</html>


              <!-- <button class="w-full h-0 group-hover:h-10 bg-quinary overflow-hidden transition-all duration-200 rounded-2xl">
                <span class="text-xl opacity-70 text-primary font-extrabold">
                  بله
                </span>
              </button> -->