cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', AddToCartView.as_view(), name='add'),
    path('addcustomcurtain/<int:product_id>/', AddCustomCurtainToCartView.as_view(), name='addcustomCurtain'),
    path('remove/<int:product_id>/', RemoveFromCartView.as_view(), name='remove'),  
    path('update/<int:product_id>/', UpdateCartView.as_view(), name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
# from website.sitemaps import StaticViewSitemap
# from blog.sitemaps import BlogSitemap
from django.conf.urls import handler404
from azbankgateways.urls import az_bank_gateways_urls


# sitemaps = {
#     "static": StaticViewSitemap,
#     'blog': BlogSitemap
# }

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/',include('payments.urls')),
    # path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'website.views.handler404'

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('Sofa/', SofaView.as_view(), name='sofa'),
    path('Sofafabric/', SofafabricView.as_view(), name='sofafabric'),
    path('Wallcoverings/', WallcoveringsView.as_view(), name='wallcovering'),
    path('Floorcoverings/', FloorcoveringsView.as_view(), name='floorcovering'),
    path('Cornice/', CorniceView.as_view(), name='cornice'),
    path('Readycurtain/', ReadycurtainView.as_view(), name='readycurtain'),
    path('Customcurtain/', CustomcurtainView.as_view(), name='customcurtain'),
    path('zebracurtain/', ZebracurtainView.as_view(), name='zebracurtain'),
    path('<int:product_id>/', ProductDetailView.as_view(), name='product_detail'),
]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('sofas/', SofasView.as_view(), name='sofas'),

    # other paths...
]

handler404 = 'website.views.handler404'

products/models.py
from django.db import models
from autoslug import AutoSlugField
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext as _



class Image(models.Model):
    image = models.ImageField(upload_to='product_images/', verbose_name='تصویر')
    image_number = models.PositiveIntegerField(verbose_name='شماره تصویر')

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = 'تصاویر'

    def __str__(self):
        return f"Image {self.image_number}"

class Category(MPTTModel):

    category_name = models.CharField(max_length=200, unique=True, verbose_name='نام دسته')
    parent = TreeForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children', db_index=True)
    slug = AutoSlugField(populate_from='category_name', unique=True)

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
    
    class MPTTMeta:
        order_insertion_by = ['category_name']

    def __str__(self):
        return self.category_name



class Texture(models.Model):
    code = models.CharField(max_length=50, verbose_name='کد تکسچر')
    image = models.ImageField(upload_to='texture_images/', verbose_name='تصویر تکسچر')

    class Meta:
        verbose_name = 'تصویر تکسچر'
        verbose_name_plural = 'تصاویر تکسچر ها'

    def __str__(self):
        return f"Texture {self.code}"

class Price(models.Model):
    PRICE_UNIT = [
        ('Square_meters', 'متر مربع'),
        ('roll', 'رول'),
        ('Branch', 'شاخه'),
        ('number', 'عدد'),
    ]
    UNIT_TRANSLATION = {
        'Square_meters': 'متر مربع',
        'roll': 'رول',
        'Branch': 'شاخه',
        'number': 'عدد',
    }
    unit = models.CharField(max_length=13, choices=PRICE_UNIT, default='number', verbose_name='واحد قیمت')
    price_wholesale = models.IntegerField(verbose_name='قیمت عمده')
    price_retail = models.IntegerField(verbose_name='قیمت خرده')

    class Meta:
        verbose_name = 'قیمت'
        verbose_name_plural = 'قیمت‌ها'

    def display_price(self):
        unit_str = f'واحد: {self.get_translated_unit()}' if self.unit is not None else ''
        wholesale_str = f'قیمت عمده: {self.price_wholesale}' if self.price_wholesale is not None else ''
        retail_str = f'قیمت خرده: {self.price_retail}' if self.price_retail is not None else ''

        price_str = ' | '.join(filter(None, [unit_str, wholesale_str, retail_str]))
        return price_str

    def get_translated_unit(self):
        return self.UNIT_TRANSLATION.get(self.unit, self.unit)

    def __str__(self):
        return self.display_price()

class Dimensions(models.Model):
    LENGTH_UNIT = [
        ('meter', 'متر'),
        ('millimeter', 'میلیمتر'),
        ('centimeter', 'سانتیمتر'),
        ('inch', 'اینچ'),
    ]

    WIDTH_UNIT = [
        ('meter', 'متر'),
        ('millimeter', 'میلیمتر'),
        ('centimeter', 'سانتیمتر'),
        ('inch', 'اینچ'),
    ]

    THICKNESS_UNIT = [
        ('meter', 'متر'),
        ('millimeter', 'میلیمتر'),
        ('centimeter', 'سانتیمتر'),
        ('inch', 'اینچ'),
    ]
    UNIT_TRANSLATION = {
        'meter': 'متر',
        'millimeter': 'میلیمتر',
        'centimeter': 'سانتیمتر',
        'inch': 'اینچ',
    }
    # متراژ رو اضاف کن

    length_unit = models.CharField(max_length=13, null=True, blank=True, choices=LENGTH_UNIT, default='meter', verbose_name='واحد اندازه گیری طول')
    length = models.DecimalField(max_digits=10, null=True, blank=True, decimal_places=0, verbose_name='طول')

    width_unit = models.CharField(max_length=13, null=True, blank=True, choices=WIDTH_UNIT, default='meter', verbose_name='واحد اندازه گیری عرض')
    width = models.DecimalField(max_digits=10, null=True, blank=True, decimal_places=0, verbose_name='عرض')

    thickness_unit = models.CharField(max_length=13, null=True, blank=True, choices=THICKNESS_UNIT, default='millimeter', verbose_name='واحد اندازه گیری ضخامت')
    thickness = models.DecimalField(max_digits=10, null=True, blank=True, decimal_places=0, verbose_name='ضخامت')
    
    def get_dimensions_display(self, obj):
        if obj.dimensions:
            return obj.dimensions.display_dimensions()
        else:
            return 'No dimensions available'
        
    def get_length_display(self):
        return f'{self.length} {self.UNIT_TRANSLATION.get(self.length_unit, "")}' if self.length is not None else ''

    def get_width_display(self):
        return f'{self.width} {self.UNIT_TRANSLATION.get(self.width_unit, "")}' if self.width is not None else ''

    def get_thickness_display(self):
        return f'{self.thickness} {self.UNIT_TRANSLATION.get(self.thickness_unit, "")}' if self.thickness is not None else ''

    def display_dimensions(self):
        length_str = f"طول: {self.get_length_display()}"
        width_str = f"عرض: {self.get_width_display()}"
        thickness_str = f"ضخامت: {self.get_thickness_display()}"

        dimensions_str = ' | '.join(filter(None, [length_str, width_str, thickness_str]))
        return dimensions_str
    # update this

    
    def __str__(self):
        return self.display_dimensions()
    
    def create_from_string(cls, dimension_string):
        dimensions_list = dimension_string.split('*')
        if len(dimensions_list) == 2:
            length, width = map(int, dimensions_list)
            length, width = max(length, width), min(length, width)
            return cls.objects.create(length=length, width=width)
        else:
            return None

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='نام دسته')
    title = models.CharField(max_length=250, verbose_name='نام محصول')
    description = models.TextField(null=True, blank=True,verbose_name='توضیحات')
    price = models.ForeignKey(Price, on_delete=models.CASCADE, null=True, blank=True, related_name='products_price' ,verbose_name='قیمت')
    dimensions = models.ForeignKey(Dimensions,on_delete=models.CASCADE, null=True, blank=True, related_name='products_dimensions',verbose_name='ابعاد')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    product_code = models.CharField(max_length=3, verbose_name='کد محصول')
    images = models.ManyToManyField(Image, related_name='products', verbose_name='تصاویر')
    textures = models.ManyToManyField(Texture,blank=True, related_name='products', verbose_name='تکسچرها')
    slug = AutoSlugField(populate_from='title', unique=True)

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'همه محصولات'
        indexes = [
            models.Index(fields=['title']),
            models.Index(fields=['date_created']),
        ]

    def __str__(self):
        return self.title
    
    def get_selected_texture(self, texture_code):
        try:
            return self.textures.get(code=texture_code)
        except Texture.DoesNotExist:
            # Handle the case when the texture is not found
            return None


class Decoration(Product):
    class Meta:
        verbose_name = 'دکراسیون'
        verbose_name_plural = 'دکراسیون'

class Wallcoverings(Decoration):
    class Meta:
        verbose_name = 'پوشش دیواری'
        verbose_name_plural = 'پوشش‌های دیواری'


class Floorcoverings(Decoration):
    glue_10kg = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True,related_name='glue_10kg', verbose_name='چسب 10 کیلویی')
    glue_4kg = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True,related_name='glue_4kg', verbose_name='چسب 4 کیلویی')

    class Meta:
        verbose_name = 'پوشش کف'
        verbose_name_plural = 'پوشش‌های کف'


class Cornice(Decoration):
    Cornice_TRANSLATION = {
        '7': '7 سانتی',
        '9': '9 سانتی',
        'Gordeh': '(پایان کار) گرده',
        'Miane': 'میانه',
        'Tasho': 'تاشو',
        'Scouti': 'اسکوتیا',
    }
    Cornic_7 = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True, related_name='cornices_7' ,verbose_name='قرنیز 7 سانتی')
    Cornic_9 = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True, related_name='cornices_9' ,verbose_name='قرنیز 9 سانتی')

    Gordeh = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True, related_name='Gordeh' ,verbose_name='(پایان کار) گرده')    
    Miane = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True, related_name='Miane' ,verbose_name='میانه')    
    Tasho = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True, related_name='Tasho' ,verbose_name='تاشو')    
    Scouti = models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True, related_name='Scouti' ,verbose_name='اسکوتیا')    


    class Meta:
        verbose_name = 'قرنیز'
        verbose_name_plural = 'قرنیزها'

class Curtain(Product):
    class Meta:
        verbose_name = 'پرده'
        verbose_name_plural = 'پرده‌ها'

class Readycurtain(Curtain):
    curtain_rod = models.BooleanField(default=False, verbose_name='چوب پرده')

    class Meta:
        verbose_name = 'پرده آماده'
        verbose_name_plural = 'پرده‌های آماده'

class Zebracurtain(Curtain):

    class Meta:
        verbose_name = 'پرده زبرا'
        verbose_name_plural = 'پرده‌های زبرا'
    
class Customcurtain(Curtain):
    curtain_rod = models.ForeignKey(Price,on_delete=models.CASCADE,default=False, verbose_name='چوب پرده')
    curtain_model = models.CharField(max_length=50,null=True,blank=True, verbose_name='مدل پرده')
    side_fabric = models.CharField(max_length=50,null=True,blank=True, verbose_name='پارچه کنار')
    accessory = models.ManyToManyField(Product,blank=True, related_name='Customcurtain_accessories', verbose_name='اکسسوری')

    class Meta:
        verbose_name = 'پرده سفارشی'
        verbose_name_plural = 'پرده‌های سفارشی'
        
    def get_class_name(self):
        return self.__class__.__name__

class Sofafabric(Product):
    class Meta:

products/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Product
from django.views.generic import ListView
from .models import *




class ProductDetailView(View):
    template_name = 'products/product_detail/product_detail.html'

    def get_class_name_for_record(self, record_id):
        try:
            cornice = Cornice.objects.get(id=record_id)
            return 'cornice', cornice
        except Cornice.DoesNotExist:
            pass

        try:
            floorcoverings =Floorcoverings.objects.get(id=record_id)
            return 'Floorcoverings', floorcoverings
        except Floorcoverings.DoesNotExist:
            pass

        try:
            custom_curtain = Customcurtain.objects.get(id=record_id)
            return 'Customcurtain', custom_curtain
        except Customcurtain.DoesNotExist:
            pass

        return None, None

    def get(self, request, product_id, *args, **kwargs):
        class_name, products = self.get_class_name_for_record(product_id)
        print(f"class name : {class_name}")

        if class_name=='cornice':
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product,'cornice': products, 'class_name': class_name}
        elif class_name=='Customcurtain':
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product,'custom_curtain':products, 'class_name': class_name}
        elif class_name=='Floorcoverings':
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product,'Floorcoverings':products, 'class_name': class_name}
        else:
            product = get_object_or_404(Product, pk=product_id)
            context = {'product': product, 'class_name': class_name}

        return render(request, self.template_name, context)

    
class SofaView(View):
    template_name = 'products/product_home/sofa.html'

    def get(self, request, *args, **kwargs):
        sofas = Sofa.objects.all()
        context = {'sofas': sofas}
        return render(request, self.template_name, context)
    
class SofafabricView(View):
    template_name = 'products/product_home/sofafabric.html'

    def get(self, request, *args, **kwargs):
        sofafabrics = Sofafabric.objects.all()
        context = {'sofafabrics': sofafabrics}
        return render(request, self.template_name, context)
    
class WallcoveringsView(View):
    template_name = 'products/product_home/wallcovering.html'

    def get(self, request, *args, **kwargs):
        wallcoverings = Wallcoverings.objects.all()
        context = {'wallcoverings': wallcoverings}
        return render(request, self.template_name, context)
    
class FloorcoveringsView(View):
    template_name = 'products/product_home/floorcovering.html'

    def get(self, request, *args, **kwargs):
        floorcoverings = Floorcoverings.objects.all()
        context = {'floorcoverings': floorcoverings}
        return render(request, self.template_name, context)
    
class CorniceView(View):
    template_name = 'products/product_home/cornice.html'

    def get(self, request, *args, **kwargs):
        cornices = Cornice.objects.all()
        context = {'cornices': cornices}  
        return render(request, self.template_name, context)

class ReadycurtainView(View):
    template_name = 'products/product_home/Readycurtain.html'

    def get(self, request, *args, **kwargs):
        readycurtains = Readycurtain.objects.all()
        context = {'readycurtains': readycurtains}
        return render(request, self.template_name, context)
    
class CustomcurtainView(View):
    template_name = 'products/product_home/customcurtain.html'

    def get(self, request, *args, **kwargs):
        customcurtains = Customcurtain.objects.all()
        context = {'customcurtains': customcurtains}
        return render(request, self.template_name, context)
    
class ZebracurtainView(View):
    template_name = 'products/product_home/zebracurtain.html'

    def get(self, request, *args, **kwargs):
        Zebracurtains = Zebracurtain.objects.all()
        context = {'Zebracurtains': Zebracurtains}
        return render(request, self.template_name, context)





class SearchResultsView(ListView):
    model = Product
    template_name = 'products/search_results.html'
    context_object_name = 'results'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        return Product.objects.filter(title__icontains=query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context

templates/products/product_home/Readycurtain.html
{% extends 'products/base_products.html' %}
{% load static %}
      <!-- main-area -->
    {% block content %}
    <div class="px-36 2xl:px-10 py-4 bg-secondary h-28 flex justify-center md:!px-3 md:h-fit md:py-2 ">
      <section class="w-full h-full bg-secondary ">
          <h1 class="text-3xl font-extrabold text-primary md:text-lg">
              پرده
          </h1>
          <div class="w-full h-fit flex items-center gap-1 text-xl font-normal text-primary mt-2 cursor-pointer md:text-sm">
              <a href="{% url 'website:home' %}">
                  خانه
              </a>
              <img src="data:image/svg+xml,%3csvg%20width='22'%20height='22'%20viewBox='0%200%2022%2022'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%3e%3crect%20width='22'%20height='22'%20transform='matrix(1%200%200%20-1%200%2022)'%20fill='url(%23pattern0)'/%3e%3cdefs%3e%3cpattern%20id='pattern0'%20patternContentUnits='objectBoundingBox'%20width='1'%20height='1'%3e%3cuse%20xlink:href='%23image0_638_2126'%20transform='scale(0.0192308)'/%3e%3c/pattern%3e%3cimage%20id='image0_638_2126'%20width='52'%20height='52'%20xlink:href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAYAAADFeBvrAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtElEQVR4nO3ZwQnCQBCF4alJD7Ggt38NuXm1WcUOFFHQg4mKh51Z3gdbwM9MwpJEmJmZLQMmYI4RSNq21k7ApbV2iFFieJyyUXoTUzZKKzHlori/AM5rMS9nLj8ZnucWPUVWckxS8mSSkieTlDyZpOTJJCVPJjFgAxy/vWxK2kV2OApPqhu8fnj9uvH64fXrx+uH16+foT4F//hM7aMS1qNqxXyIqhmzEFU7ZsifxmZmFn+6Ajj7X4aUiCzdAAAAAElFTkSuQmCC'/%3e%3c/defs%3e%3c/svg%3e" class="size-4" alt="">
              <a href="{% url 'products:readycurtain' %}">پرده آماده</a>
          </div>
      </section>
  </div>
    <main class="w-full h-fit px-48 2xl:px-16 md:!px-0 py-10 md:py-5 flex flex-col gap-10 md:gap-5 items-center bg-tertiary">
      <section class="w-full flex justify-start items-start flex-col gap-5">
            <div class="flex gap-4">
                <a href="{% url 'products:readycurtain' %}">
                <button class="py-2 px-8 font-extrabold bg-secondary text-senary rounded-2xl text-2xl min-w-40">پرده آماده</button>
                </a>
                <a href="{% url 'products:customcurtain' %}">
                <button class="py-2 px-8 font-extrabold bg-secondary text-senary rounded-2xl text-2xl min-w-40">پرده سفارشی</button>
                </a>
                <a href="{% url 'products:zebracurtain' %}">
                  <button class="py-2 px-8 font-extrabold bg-secondary text-senary rounded-2xl text-2xl min-w-40">زبرا شیپ</button>
                </a>
            </div>
        </section> 
        <section class="w-full h-fit bg-secondary p-10 md:p-5 grid grid-cols-4 xl:grid-cols-2 gap-5 rounded-4xl">
            {% for product in readycurtains %}
            <div class="w-full h-fit flex flex-col gap-2 p-2 bg-white rounded-4xl md:rounded-lg">
              <a href="{% url 'products:product_detail' product_id=product.id %}">
                <img src="{{ product.images.first.image.url }}" class="w-full h-60 md:h-auto md:aspect-video md:rounded-lg object-cover rounded-3xl " alt="{{ product.title }}">
                <h4 class="text-primary text-xl md:text-base font-bold">{{ product.title }}</h4>
              </a>
                <div class="w-full flex justify-end">
                  <span class="text-primary text-lg md:text-sm font-bold">
                   {% if user.is_authenticated %}
                         {% if user.customer_type == 'wholesale' %}
                            <span class="text-primary text-lg md:text-sm font-bold">
                            {{ product.price.price_wholesale }} تومان
                            </span>
                        {% else %}
                        <span class="text-primary text-lg md:text-sm font-bold">
                            {{ product.price.price_retail }} تومان
                        </span>
                        {% endif %}
                    {% else %}
                    <span class="text-primary text-lg md:text-sm font-bold">
                      {{ product.price.price_retail }} تومان
                    </span>
                    {% endif %}
                </span>
                </div>
                <div class="w-full flex justify-center items-center">
                    <a href="{% url 'products:product_detail' product_id=product.id %}">
                    <button class="bg-primary px-6 py-2 text-tertiary text-lg md:text-sm md:px-3 font-bold rounded-xl">افزودن به سبد </button>
                    </a>
                </div>
            </div>
            {% endfor %}
          </section>
        </main>
    {% endblock content %}

templates/products/product_home/wallcovering.html
{% extends 'products/base_products.html' %}
{% load static %}
      <!-- main-area -->
    {% block content %}
    <div class="px-36 2xl:px-10 py-4 bg-secondary h-28 flex justify-center md:!px-3 md:h-fit md:py-2 ">
      <section class="w-full h-full bg-secondary ">
          <h1 class="text-3xl font-extrabold text-primary md:text-lg">
              دکوراسیون
          </h1>
          <div class="w-full h-fit flex items-center gap-1 text-xl font-normal text-primary mt-2 cursor-pointer md:text-sm">
              <a href="{% url 'website:home' %}">
                  خانه
              </a>
              <img src="data:image/svg+xml,%3csvg%20width='22'%20height='22'%20viewBox='0%200%2022%2022'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%3e%3crect%20width='22'%20height='22'%20transform='matrix(1%200%200%20-1%200%2022)'%20fill='url(%23pattern0)'/%3e%3cdefs%3e%3cpattern%20id='pattern0'%20patternContentUnits='objectBoundingBox'%20width='1'%20height='1'%3e%3cuse%20xlink:href='%23image0_638_2126'%20transform='scale(0.0192308)'/%3e%3c/pattern%3e%3cimage%20id='image0_638_2126'%20width='52'%20height='52'%20xlink:href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAYAAADFeBvrAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtElEQVR4nO3ZwQnCQBCF4alJD7Ggt38NuXm1WcUOFFHQg4mKh51Z3gdbwM9MwpJEmJmZLQMmYI4RSNq21k7ApbV2iFFieJyyUXoTUzZKKzHlori/AM5rMS9nLj8ZnucWPUVWckxS8mSSkieTlDyZpOTJJCVPJjFgAxy/vWxK2kV2OApPqhu8fnj9uvH64fXrx+uH16+foT4F//hM7aMS1qNqxXyIqhmzEFU7ZsifxmZmFn+6Ajj7X4aUiCzdAAAAAElFTkSuQmCC'/%3e%3c/defs%3e%3c/svg%3e" class="size-4" alt="">
              <a href="{% url 'products:wallcovering' %}">پوشش های دیواری</a>
          </div>
      </section>
  </div>
    <main class="w-full h-fit px-48 2xl:px-16 md:!px-0 py-10 md:py-5 flex flex-col gap-10 md:gap-5 items-center bg-tertiary">
      <section class="w-full flex justify-start items-start flex-col gap-5">
            <div class="flex gap-4">
                <a href="{% url 'products:wallcovering' %}">
                <button class="py-2 px-8 font-extrabold bg-secondary text-senary rounded-2xl text-2xl min-w-40">پوشش های دیواری</button>
                </a>
                <a href="{% url 'products:floorcovering' %}">
                <button class="py-2 px-8 font-extrabold bg-secondary text-senary rounded-2xl text-2xl min-w-40">پوشش های کف</button>
                </a>
                <a href="{% url 'products:cornice' %}">
                  <button class="py-2 px-8 font-extrabold bg-secondary text-senary rounded-2xl text-2xl min-w-40">قرنیز</button>
                </a>
            </div>
        </section> 
        <section class="w-full h-fit bg-secondary p-10 md:p-5 grid grid-cols-4 xl:grid-cols-2 gap-5 rounded-4xl">
            {% for product in wallcoverings %}
            <div class="w-full h-fit flex flex-col gap-2 p-2 bg-white rounded-4xl md:rounded-lg">
              <a href="{% url 'products:product_detail' product_id=product.id %}">
                <img src="{{ product.images.first.image.url }}" class="w-full h-60 md:h-auto md:aspect-video md:rounded-lg object-cover rounded-3xl " alt="{{ product.title }}">
                <h4 class="text-primary text-xl md:text-base font-bold">{{ product.title }}</h4>
              </a>
                <div class="w-full flex justify-end">
                  <span class="text-primary text-lg md:text-sm font-bold">
                   {% if user.is_authenticated %}
                         {% if user.customer_type == 'wholesale' %}
                            <span class="text-primary text-lg md:text-sm font-bold">
                            {{ product.price.price_wholesale }} تومان
                            </span>
                        {% else %}
                        <span class="text-primary text-lg md:text-sm font-bold">
                            {{ product.price.price_retail }} تومان
                        </span>
                        {% endif %}
                    {% else %}
                    <span class="text-primary text-lg md:text-sm font-bold">
                      {{ product.price.price_retail }} تومان
                    </span>
                    {% endif %}
                </span>
                </div>
                <form method="post" action="{% url 'cart:add' product_id=product.id %}">
                  {% csrf_token %}
                  <input type="hidden" name="product_id" value="{{ product.id }}">
                  <input type="hidden" name="quantity" value="1">
                  <button type="submit" class="bg-primary px-6 py-2 text-tertiary text-lg md:text-sm md:px-3 font-bold rounded-xl">افزودن به سبد</button>
              </form>
            </div>
            {% endfor %}
          </section>
        </main>
    {% endblock content %}