accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('send_verification_code/', SendVerificationCodeView.as_view(), name='send_verification_code'),
    path('login_with_confirmation_code/', LoginWithConfirmationCodeView.as_view(), name='login_with_confirmation_code'),
    # path('logout/', logout_view, name='logout'),
    path('signup/', CustomerSignUpView.as_view(), name='signup'),
    path('update/', UpdateUserView.as_view(), name='update'),
    path('Partnersignup/', WholesaleCustomerView.as_view(), name='PartnerSignUp'),
    path('Partnerupdate/', WholesaleCustomerUpdateView.as_view(), name='Partnerupdate'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', AddToCartView.as_view(), name='add'),
    path('addcustomcurtain/<int:product_id>/', AddCustomCurtainToCartView.as_view(), name='addcustomCurtain'),
    path('remove/<int:product_id>/', RemoveFromCartView.as_view(), name='remove'),  
    path('update/<int:product_id>/', UpdateCartView.as_view(), name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
# from website.sitemaps import StaticViewSitemap
# from blog.sitemaps import BlogSitemap
from django.conf.urls import handler404
from azbankgateways.urls import az_bank_gateways_urls


# sitemaps = {
#     "static": StaticViewSitemap,
#     'blog': BlogSitemap
# }

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/',include('payments.urls')),
    # path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'website.views.handler404'

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('Sofa/', SofaView.as_view(), name='sofa'),
    path('Sofafabric/', SofafabricView.as_view(), name='sofafabric'),
    path('Wallcoverings/', WallcoveringsView.as_view(), name='wallcovering'),
    path('Floorcoverings/', FloorcoveringsView.as_view(), name='floorcovering'),
    path('Cornice/', CorniceView.as_view(), name='cornice'),
    path('Readycurtain/', ReadycurtainView.as_view(), name='readycurtain'),
    path('Customcurtain/', CustomcurtainView.as_view(), name='customcurtain'),
    path('zebracurtain/', ZebracurtainView.as_view(), name='zebracurtain'),
    path('<int:product_id>/', ProductDetailView.as_view(), name='product_detail'),
]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('sofas/', SofasView.as_view(), name='sofas'),

    # other paths...
]

handler404 = 'website.views.handler404'

templates/Phone.html
<aside class="w-0 h-screen overflow-hidden hidden lg:flex flex-col absolute top-0 left-0 bg-white z-50 transition-all duration-500 py-4" id="phoneMenu">
    <button class="flex flex-col justify-around w-6 h-6 bg-transparent border-none cursor-pointer z-10 focus:outline-none mr-5" id="hamburger">
      <span class="block w-6 h-0.5 bg-black transition-transform duration-200 ease-in-out"></span>
      <span class="block w-6 h-0.5 bg-black transition-transform duration-200 ease-in-out"></span>
      <span class="block w-6 h-0.5 bg-black transition-transform duration-200 ease-in-out"></span>
    </button>  
    <div class="w-full">
      <div class="w-full bg-white">
        <button class="w-full flex items-center p-4 border-b border-gray-200 menu-button" data-target="nestedItems1">
          <span>مبل و پارچه مبلی</span>
        </button>
        <div class="hidden menu-content" id="nestedItems1">
          <ul class="list-disc">
            <li>
              <a href="{% url 'products:sofa' %}" class="w-full flex items-center text-sm p-4 pr-8">
                <span>مبل</span>
              </a>
            </li>
          <ul class="list-disc">
            <li>
              <a href="{% url 'products:sofafabric' %}" class="w-full flex items-center text-sm p-4 pr-8">
                <span>پارچه مبلی</span>
              </a>
            </li>
          </ul>

        </div>
        <button class="w-full flex items-center p-4 border-b border-gray-200 menu-button" data-target="nestedItems2">
          <span>دکراسیون</span>
        </button>
        <div class="pl-4 hidden menu-content" id="nestedItems2">
          <a href="{% url 'products:wallcovering' %}" class="w-full flex items-center p-4 text-sm pr-8">
            <span>پوشش های دیواری</span>
          </a>
          <a href="{% url 'products:floorcovering' %}" class="w-full flex items-center p-4 text-sm pr-8">
            <span>پوشش های کف</span>
          </a>
          <a href="{% url 'products:floorcovering' %}" class="w-full flex items-center p-4 text-sm pr-8">
            <span>قرنیز</span>
          </a>
        </div>
        <button class="w-full flex items-center p-4 border-b border-gray-200 menu-button" data-target="nestedItems2">
          <span>پرده</span>
        </button>
        <div class="pl-4 hidden menu-content" id="nestedItems2">
          <a href="{% url 'products:readycurtain' %}" class="w-full flex items-center p-4 text-sm pr-8">
            <span>پرده آماده</span>
          </a>
          <a href="{% url 'products:customcurtain' %}" class="w-full flex items-center p-4 text-sm pr-8">
            <span>پرده سفارشی</span>
          </a>
        </div>
      </div>
    </div>
  </aside>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>طراحان</title>
    <link rel="stylesheet" href="{% static '/fonts/fonts.css' %}">
    <link rel="stylesheet" crossorigin href="{% static '/assets/index-zkCL8-vd.css' %}">
    <link rel="shortcut icon" href="{% static '/assets/tarahanIcon-thsqZuN2.svg' %}" type="image/x-icon">
    <link rel="stylesheet" crossorigin href="{% static '/assets/alert.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <script type="module" crossorigin src="{% static '/assets/index-xVh7E-Ed.js' %}"></script>
  </head>
  <body dir="rtl" class="bg-tertiary relative">
    {% include 'nav.html' %}
    <nav class="w-full h-14 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.15)] px-4 hidden lg:flex justify-between items-center">
      <a href="{% url 'website:home' %}">
      <img src="{% static '/images/tarahanIcon.svg' %}" alt="" class="size-10 aspect-square">
      </a>
      <button class="flex flex-col justify-around w-6 h-6 bg-transparent border-none cursor-pointer z-10 focus:outline-none" id="hamburger">
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
        <span class="block w-6 h-0.5 bg-black transition-transform duration-500 ease-in-out"></span>
      </button>    
    </nav>
    {% include 'Phone.html' %}


    <!-- main-area -->
    {% block content %} 
    {% endblock content %}
    <!-- main-area-end -->
    {% include 'footer.html' %}
    </body> 
  </html>
  

templates/nav.html
{% load static %}
<nav class="w-full  h-24 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.15)] px-36 2xl:px-10 flex justify-between items-center lg:hidden">
    <div class="w-fit flex gap-6 items-center">
      <a href="{% url 'website:home' %}">
        <img src="{% static '/images/tarahanIcon.svg' %}" alt="" class="w-16 h-16 aspect-square">
      </a>
      <div class=" flex gap-6 ">
        <div class="flex justify-center items-center gap-2 cursor-pointer relative group">
          <a href="{% url 'website:sofas' %}">
          <span class="text-primary text-xl font-extrabold  text-center 2xl:text-base">مبل و پارچه مبلی</span>
          </a>
          <img src="{% static '/icons/chevronDown.svg' %}" alt="" class="w-5 h-5 group-hover:rotate-180 transition-all">
          <div class="absolute right-0 top-full translate-y-3 text-white z-10 bg-white shadow-lg overflow-hidden min-w-40 w-full rounded-2xl h-0 transition-all duration-200 px-3 flex flex-col gap-2 group-hover:h-20">
            <a href="{% url 'products:sofa' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">مبل</a>
            <a href="{% url 'products:sofafabric' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">پارچه مبلی</a>
          </div>
        </div>
        <div class="flex justify-center items-center gap-2 cursor-pointer relative group">
          <span class="text-primary text-xl font-extrabold  text-center 2xl:text-base">دکراسیون</span>
          <img src="{% static '/icons/chevronDown.svg' %}" alt="" class="w-5 h-5 group-hover:rotate-180 transition-all">
          <div class="absolute right-0 top-full translate-y-3 text-white z-10 bg-white shadow-lg overflow-hidden min-w-40 w-full rounded-2xl h-0 transition-all duration-200 px-3 flex flex-col gap-2 group-hover:h-20">
            <a href="{% url 'products:wallcovering' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">پوشش های دیواری</a>
            <a href="{% url 'products:floorcovering' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">پوشش های کف</a>
            <a href="{% url 'products:floorcovering' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">قرنیز</a>
          </div>
        </div>
        <div class="flex justify-center items-center gap-2 cursor-pointer relative group">
          <span class="text-primary text-xl font-extrabold  text-center 2xl:text-base">پرده</span>
          <img src="{% static '/icons/chevronDown.svg' %}" alt="" class="w-5 h-5 group-hover:rotate-180 transition-all">
          <div class="absolute right-0 top-full translate-y-3 text-white z-10 bg-white shadow-lg overflow-hidden min-w-40 w-full rounded-2xl h-0 transition-all duration-200 px-3 flex flex-col gap-2 group-hover:h-fit group-hover:py-3">
            <a href="{% url 'products:readycurtain' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">پرده آماده</a>
            <a href="{% url 'products:customcurtain' %}" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">پرده سفارشی</a>
            <a href="" class="text-quaternary text-base mt-3 hover:text-primary font-extrabold">زبرا شیپ</a>
          </div>
        </div>
      </div>
    </div>
    <div class="w-fit flex gap-3 justify-start items-center flex-row-reverse">
      <a href="{% url 'accounts:PartnerSignUp' %}" class="button-link">
        <button class="w-fit h-12 2xl:h-8 2xl:rounded-lg 2xl:text-base 2xl:py-0 rounded-2xl bg-secondary px-10 py-2 text-primary text-xl font-extrabold">همکاری</button>
    </a>
      <div class="min-w-12 w-fit h-12 2xl:h-8 2xl:min-w-8 2xl:rounded-lg bg-secondary flex justify-center items-center rounded-2xl p-2 cursor-pointer group ">
        <div class="w-0 overflow-hidden transition-all duration-300 opacity-0 group-hover:w-20 group-hover:opacity-100">
          <a href="{% url 'website:about' %}">
          <p  class="w-20 h-fit">تماس با ما</p>
          </a>
        </div>
        <img src="{% static '/icons/phone.svg' %}" alt="" class="size-8 2xl:size-4 aspect-square">
      </div>
      <div id="loginButton" class="min-w-12 w-fit h-12 2xl:h-8 2xl:min-w-8 2xl:rounded-lg bg-secondary flex justify-center items-center rounded-2xl p-2 cursor-pointer group">
        <div class="w-0 overflow-hidden transition-all duration-300 opacity-0 group-hover:w-24 group-hover:opacity-100">
          <p class="w-24 h-fit">حساب کاربری</p>
        </div>
        <img src="{% static '/icons/user.svg' %}" alt="" class="size-8 2xl:size-4 aspect-square">
      </div>
      <div class="min-w-12 w-fit h-12 2xl:h-8 2xl:min-w-8 2xl:rounded-lg bg-secondary flex justify-center items-center rounded-2xl p-2 cursor-pointer group">
        <a href="{% url 'cart:cart' %}" class="group">
            <div class="w-0 overflow-hidden transition-all duration-300 opacity-0 group-hover:w-20 group-hover:opacity-100">
              <p class="w-20 h-fit">سبد خرید</p>
            </div>
          </a>          
        <img src="{% static '/icons/ShoppingCart.svg' %}" alt="" class="size-8 2xl:size-4 aspect-square">
      </div>
      <form action="{% url 'products:search_results' %}" method="GET">
        <div class="min-w-12 w-fit h-12 2xl:h-8 2xl:min-w-8 2xl:rounded-lg bg-secondary flex justify-center items-center rounded-2xl p-2 cursor-pointer group">
            <div class="w-0 h-full overflow-hidden transition-all duration-300 opacity-0 group-hover:w-40 group-hover:opacity-100">
                <input name="q" class="w-40 h-full bg-secondary !border-none !outline-none" placeholder="جست و جو"/>
            </div>
            <img src="{% static '/icons/Search.svg' %}" alt="" class="size-8 2xl:size-4 aspect-square">
            <button type="submit" class="hidden"></button>
        </div>
    </form>
    </div>
  </nav>
  {% include 'website/goftino.html' %}
  {% include 'website/messages.html' %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
    <h1>Order Placed Successfully!</h1>
    <!-- Add more details about the order if needed -->
{% endblock %}